datasets:
  mushroom:
    column_mapping:
      categorical_features:
        - 'cap-shape'
        - 'cap-surface'
        - 'cap-color'
        - 'does-bruise-or-bleed'
        - 'gill-attachment'
        - 'gill-spacing'
        - 'gill-color'
        - 'stem-root'
        - 'stem-surface'
        - 'stem-color'
        - 'veil-type'
        - 'veil-color'
        - 'has-ring'
        - 'ring-type'
        - 'spore-print-color'
        - 'habitat'
        - 'season'
      numerical_features:
        - 'cap-diameter'
        - 'stem-height'
        - 'stem-width'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - classification_performance
    reference_file: ./datasets/mushroom/reference.csv
service:
  calculation_period_sec: 2
  min_reference_size: 5
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 3
